name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: SSH into GCP and deploy
      run: |
        gcloud compute ssh my-vm-instance --zone us-central1-a --command "
        cd /home/user && git clone https://github.com/adminjoy/MyDockerWebsite.git || (cd MyDockerWebsite && git pull)
        cd MyDockerWebsite
        docker stop website || true
        docker rm website || true
        docker build -t website .
        docker run -d -p 80:80 --name website website
        "

